export interface TechGroup {
  category: string;
  items: string[];
}

export interface Project {
  slug: string;
  title: string;
  tagline: string;
  year: string;
  status: "Live" | "In Development" | "Completed";
  tags: string[];
  architecture: string[];
  overview: string;
  problemStatement: string;
  researchMotivation: string;
  systemArchitecture: string;
  techStack: TechGroup[];
  implementation: string[];
  challenges: string[];
  futureScope: string[];
  githubUrl: string;
  liveUrl?: string;
}

export const projects: Project[] = [
  {
    slug: "neural-architecture-inventor",
    title: "Neural Architecture Inventor",
    tagline:
      "An AutoML platform that designs, trains, and evaluates neural network architectures for tabular datasets.",
    year: "2025 — Present",
    status: "In Development",
    tags: ["AutoML", "PyTorch", "Neural Architecture Search", "FastAPI"],
    architecture: [
      "User uploads dataset",
      "FastAPI backend",
      "Preprocessing & validation pipeline",
      "Neural Architecture Search engine",
      "Optuna hyperparameter optimization",
      "PostgreSQL + Redis",
      "React dashboard with results & SHAP explanations",
    ],
    overview:
      "Neural Architecture Inventor (ANI) is an AutoML platform that takes a raw tabular dataset and automatically designs, trains, evaluates, and tunes neural network architectures suited to it — removing the manual trial-and-error that usually dominates early-stage modeling work.",
    problemStatement:
      "Designing a neural network for a new dataset is still a largely manual, experience-driven process: choosing layer counts, widths, activation functions, and regularization typically takes many rounds of trial and error. For non-experts and time-constrained teams, this is one of the biggest barriers to applying deep learning to everyday tabular problems.",
    researchMotivation:
      "Neural Architecture Search (NAS) and hyperparameter optimization are active research areas, but most tooling targets large-scale image or language models. This project explores how NAS techniques can be made practical and lightweight for tabular data — the most common data format in real business applications — while keeping the search interpretable through SHAP-based explanations.",
    systemArchitecture:
      "The platform is split into three layers. A FastAPI backend handles authentication, dataset ingestion, validation, and orchestration, persisting state in PostgreSQL with Redis used for caching and background job coordination. The ML engine performs preprocessing, traditional ML baselines, and a NAS routine that proposes candidate architectures, trains them, and scores them against the dataset, with Optuna driving hyperparameter search and SHAP providing feature-level explanations. A React and TypeScript frontend lets users upload datasets, monitor training runs, and compare resulting architectures side by side.",
    techStack: [
      { category: "Backend", items: ["Python", "FastAPI", "SQLAlchemy", "Pydantic"] },
      { category: "Machine Learning", items: ["PyTorch", "Scikit-learn", "Optuna", "SHAP", "Pandas", "NumPy"] },
      { category: "Frontend", items: ["React", "TypeScript", "Tailwind CSS"] },
      { category: "Infrastructure", items: ["PostgreSQL", "Redis", "Docker", "Docker Compose", "GitHub Actions"] },
    ],
    implementation: [
      "Modular backend structure separating API routes, services, ORM models, and Pydantic schemas for a clean boundary between transport and business logic.",
      "Dataset upload pipeline with validation and automated profiling before any training begins.",
      "ML engine organized into preprocessing, training, NAS, evaluation, and optimization modules so each stage can evolve independently.",
      "Optuna-driven hyperparameter search wrapped around candidate architectures generated by the NAS routine.",
      "SHAP integration to explain why a given architecture performs the way it does on a specific dataset.",
      "Containerized with Docker Compose for local development and CI via GitHub Actions.",
    ],
    challenges: [
      "Balancing search-space size against compute budget so NAS runs remain practical on modest hardware.",
      "Designing a backend schema flexible enough to represent arbitrary architectures and their training results.",
      "Keeping the asynchronous training pipeline observable so users can track long-running jobs in real time.",
    ],
    futureScope: [
      "Support for additional data modalities beyond tabular data, including time-series.",
      "Distributed training across multiple workers for larger search spaces.",
      "Exportable, production-ready model artifacts (ONNX) directly from the dashboard.",
    ],
    githubUrl: "https://github.com/kasibaffan/neural-architecture-inventor",
  },
  {
    slug: "ecosense-ai",
    title: "EcoSense AI",
    tagline:
      "A computer vision system that flags early signs of ecosystem instability by combining CNN features with fractal and entropy analysis.",
    year: "2025",
    status: "Completed",
    tags: ["TensorFlow", "Computer Vision", "Fractal Analysis", "Environmental AI"],
    architecture: [
      "Ecosystem image dataset",
      "CNN classifier (Conv2D + MaxPooling + Dense)",
      "Deep feature extraction (penultimate layer)",
      "Entropy & fractal dimension analysis",
      "Regression model (Random Forest / SVR)",
      "Tipping-point detection & visualization",
    ],
    overview:
      "EcoSense AI studies ecosystem imagery for early warning signs of ecological tipping points. A convolutional network learns visual features across ecosystem categories, and those features are then analyzed through the lens of entropy and fractal geometry to surface instability that isn't obvious from the images alone.",
    problemStatement:
      "Ecosystem degradation is often gradual and easy to miss until the damage is visible and difficult to reverse. Manual monitoring doesn't scale, and standard image classifiers only answer 'what is this' — not 'how stable is this system'. There's a gap between what deep learning models extract from images and the complexity measures ecologists actually care about.",
    researchMotivation:
      "This project asks whether tools from dynamical systems theory — Shannon entropy and fractal dimension — can be applied to the feature embeddings of a trained CNN, rather than to raw time-series data as is traditional. If the complexity of a CNN's internal representation correlates with ecological instability, it offers a lightweight, image-based early-warning signal that complements direct classification.",
    systemArchitecture:
      "A CNN (stacked Conv2D and MaxPooling layers feeding into dense layers) is trained with Keras' ImageDataGenerator on a 14-class ecosystem image dataset, using an 80/20 train/validation split. Once trained, the network's penultimate layer is used as a feature extractor, producing a compact embedding for each image. For each embedding, the pipeline computes Shannon entropy over the normalized feature distribution and a Higuchi-style fractal dimension over the feature sequence — both measures of representational complexity. These values feed Random Forest and SVR regressors (with MinMaxScaler-normalized inputs) that map complexity to an instability score. Samples whose entropy exceeds a statistical threshold (mean plus one standard deviation) are flagged as potential tipping points and plotted with Matplotlib.",
    techStack: [
      { category: "Languages", items: ["Python"] },
      { category: "Deep Learning", items: ["TensorFlow", "Keras", "CNN (Conv2D, MaxPooling, Dense)"] },
      { category: "Analysis", items: ["Entropy (SciPy)", "Fractal Dimension Analysis", "Scikit-learn"] },
      { category: "Data & Visualization", items: ["NumPy", "Pandas", "Matplotlib"] },
    ],
    implementation: [
      "Built and trained a CNN classifier over a 14-class ecosystem image dataset using Keras ImageDataGenerator with rescaling and an 80/20 train/validation split.",
      "Extracted deep feature embeddings from the trained model's penultimate dense layer as a compact representation of each image.",
      "Implemented Shannon entropy computation over normalized feature vectors to quantify representational complexity per sample.",
      "Implemented a Higuchi-style fractal dimension calculation over feature sequences to capture self-similarity and roughness as an instability signal.",
      "Trained Random Forest and SVR regressors on MinMaxScaler-normalized complexity measures, evaluated with mean squared error.",
      "Flagged potential tipping points using a mean-plus-standard-deviation entropy threshold and visualized the results with Matplotlib.",
    ],
    challenges: [
      "Adapting fractal dimension and entropy — normally computed on raw time-series — to work meaningfully over learned CNN feature embeddings.",
      "Choosing a tipping-point threshold that is statistically grounded rather than arbitrary, given the lack of labeled instability events.",
      "Working with a relatively small, imbalanced image dataset spread across 14 ecosystem categories.",
    ],
    futureScope: [
      "Validate the entropy and fractal-dimension signals against real-world ecological time-series data.",
      "Fuse image-based features with tabular environmental sensor data (temperature, humidity, soil moisture) for a multi-modal model.",
      "Package the pipeline as a continuous-monitoring tool with a dashboard for tracking instability scores over time.",
    ],
    githubUrl:
      "https://github.com/kasibaffan/Ai-model-to-predict-ecosystem-using-fractal-entropy-analysis-and-models",
  },
  {
    slug: "football-stats-companion",
    title: "Football Stats Companion",
    tagline:
      "An AI-assisted football management companion that simulates matches, scouts players, and generates tactical insight.",
    year: "2025",
    status: "Completed",
    tags: ["Flask", "LLM Integration", "Simulation", "JavaScript"],
    architecture: [
      "User",
      "JavaScript frontend",
      "Flask REST API",
      "Simulation & scouting logic",
      "LLM-generated insights",
      "JSON response to dashboard",
    ],
    overview:
      "Football Stats Companion is a lightweight football management tool that combines deterministic match simulation and player scouting with LLM-generated narrative insight, served through a Flask API to a browser-based dashboard.",
    problemStatement:
      "Football management games and analytics tools either lean entirely on hand-tuned statistical models with no narrative context, or on free-form text generation with no grounding in actual match data. Neither alone gives a user something that feels both informative and engaging.",
    researchMotivation:
      "This project investigates a middle ground: use simple, transparent simulation logic to generate the underlying data (scores, key moments, scouting attributes), then use a language model purely to narrate and contextualize that data — keeping the model's role bounded and its output grounded in numbers the system actually produced.",
    systemArchitecture:
      "A static JavaScript frontend sends requests to a Flask backend exposing REST endpoints for match simulation and player scouting. The simulation logic generates scores and key match moments programmatically, while the scouting module produces structured player attributes. These structured results are then optionally passed to an LLM, which turns the raw data into readable scouting reports and match summaries. Flask-CORS allows the frontend to be served independently of the API during development, and configuration (API keys) is loaded from environment variables via python-dotenv.",
    techStack: [
      { category: "Backend", items: ["Python", "Flask", "Flask-CORS"] },
      { category: "AI Integration", items: ["LLM API for narrative generation"] },
      { category: "Frontend", items: ["JavaScript", "HTML", "CSS"] },
      { category: "Tooling", items: ["python-dotenv"] },
    ],
    implementation: [
      "REST endpoints for match simulation, returning scores and key match moments as structured JSON.",
      "Player scouting endpoint generating structured attributes (age, position, rating) for a given player name.",
      "LLM integration layer that turns structured simulation output into natural-language summaries and scouting reports.",
      "Environment-based configuration so API credentials are never hard-coded.",
      "CORS-enabled API so the frontend can be developed and deployed independently of the backend.",
    ],
    challenges: [
      "Keeping LLM output consistent with the underlying simulated data rather than contradicting it.",
      "Designing simulation logic that feels plausible without requiring a full statistical model.",
      "Structuring the API so new game modes (e.g. season simulation) can be added without breaking existing endpoints.",
    ],
    futureScope: [
      "Persist match and scouting history in a database to support season-long analytics.",
      "Add a proper statistical model behind the simulation, informed by real team and player data.",
      "Build out a richer dashboard with charts for team and player performance over time.",
    ],
    githubUrl: "https://github.com/kasibaffan/SmartFootballCompanion",
  },
  {
    slug: "neural-chatbot",
    title: "Neural Chatbot",
    tagline:
      "A conversational AI assistant with voice input/output, intent recognition, and contextual response generation.",
    year: "2024 — 2025",
    status: "Completed",
    tags: ["Conversational AI", "Speech Recognition", "Python", "NLP"],
    architecture: [
      "User (voice or text)",
      "Speech-to-text",
      "Intent & command processing",
      "Response generation",
      "Text-to-speech output",
    ],
    overview:
      "Neural Chatbot is a desktop conversational assistant that listens for spoken or typed input, interprets intent, and responds through synthesized speech — built as an exploration of practical, locally-run conversational AI.",
    problemStatement:
      "Most consumer voice assistants are closed platforms that can't be extended or inspected. Building a personal assistant from the ground up means solving speech recognition, intent classification, response generation, and speech synthesis as a connected pipeline rather than separate demos.",
    researchMotivation:
      "The project's goal was to understand the full conversational pipeline end-to-end: how audio becomes text, how text becomes an interpreted command or query, and how a response is generated and spoken back — and to identify where rule-based logic is sufficient versus where a language model adds real value.",
    systemArchitecture:
      "Audio input is captured and converted to text via a speech recognition module. The resulting text is processed by an intent layer that distinguishes between direct commands (open an application, answer a factual query, control system functions) and open-ended conversation, which is routed to a language-model-backed response generator. Responses are converted back to audio through a text-to-speech engine, closing the loop for a hands-free interaction.",
    techStack: [
      { category: "Languages", items: ["Python"] },
      { category: "Speech", items: ["Speech Recognition", "Text-to-Speech"] },
      { category: "NLP", items: ["Intent Classification", "Language Model integration"] },
    ],
    implementation: [
      "Speech-to-text pipeline for capturing and transcribing spoken commands.",
      "Intent-routing layer separating system commands from open conversational queries.",
      "Language-model-backed response generation for open-ended questions.",
      "Text-to-speech output for fully voice-driven interaction.",
      "Iterative refactors to improve reliability of the audio capture and playback pipeline.",
    ],
    challenges: [
      "Handling ambient noise and recognition errors gracefully without breaking the conversational flow.",
      "Drawing a clean line between rule-based commands and model-generated responses.",
      "Managing latency so voice interactions feel responsive rather than scripted.",
    ],
    futureScope: [
      "Add persistent conversational memory across sessions.",
      "Replace rule-based intent matching with a lightweight trained classifier.",
      "Package the assistant as a cross-platform application.",
    ],
    githubUrl: "https://github.com/kasibaffan/jarvis-2.0",
  },
  {
    slug: "pokefolio",
    title: "Pokefolio",
    tagline:
      "A Pokémon-trainer-themed interactive portfolio that reimagines projects, skills, and stats as a playable region.",
    year: "2026",
    status: "Completed",
    tags: ["Next.js", "Three.js", "Framer Motion", "Creative Frontend"],
    architecture: [
      "Intro sequence (loading bar + typewriter)",
      "Adventure Map navigation / Zustand store",
      "Champion Team (projects as Pokémon)",
      "Trainer Stats (skills as stat hex chart)",
      "TM Vault (certifications) & Bag (tools)",
      "PokeGear (contact) & ambient 3D/canvas effects",
    ],
    overview:
      "Pokefolio reimagines a software engineer's CV as a Pokémon game region: projects become a 'Champion Team' of Pokémon with abilities and evolution stages, skills become Trainer Stats on a hex chart, certifications become collectible TM cards, and contact links become PokeGear apps.",
    problemStatement:
      "Most developer portfolios — including conventional ones — present the same information (projects, skills, certifications, contact) in the same top-to-bottom layout. The challenge was to design a genuinely interactive, memorable alternative that keeps all of that real content intact while making exploring it feel like play rather than reading a document.",
    researchMotivation:
      "This project explores how far a single, consistent metaphor — the Pokémon game's UI language of stat screens, type badges, evolution chains, and item bags — can be pushed as an information-design system for a CV. It's also a sandbox for UI engineering techniques (3D scenes, canvas particle effects, scroll-driven navigation, ambient audio, hidden easter eggs) that don't fit a minimal research-style portfolio.",
    systemArchitecture:
      "Built on the Next.js App Router as a single client-rendered page composed of section components, each mapped to a node on a persistent Adventure Map navigation (desktop) or mobile nav bar. Global UI state — active section, intro completion, unlocked achievements, audio toggle — is managed with Zustand. An intro screen with a loading bar and a custom typewriter hook gates the main content. Real projects render as 'Champion Team' Pokémon cards with type badges, abilities, and evolution-stage timelines; real skill categories map onto a Pokémon-style stat hex chart in the Trainer Stats section; certifications appear as collectible TM cards in Professor Oak's TM Vault; languages and tools appear as Bag items with flavor text; and contact links are presented as PokeGear apps. An ambient effects layer — floating background shapes, a pixel particle field, a capture-orb canvas animation, and pokeball-shaped transitions — is built with Framer Motion, GSAP, and React Three Fiber / Drei, alongside a toast-based achievement system for hidden easter eggs.",
    techStack: [
      { category: "Framework", items: ["Next.js", "React", "TypeScript", "Tailwind CSS"] },
      { category: "Animation & 3D", items: ["Framer Motion", "GSAP", "React Three Fiber", "Drei", "Three.js"] },
      { category: "State Management", items: ["Zustand"] },
      { category: "UI", items: ["react-icons"] },
    ],
    implementation: [
      "Modeled real projects, skills, and certifications as typed Pokémon-style data — types, abilities, evolution stages, stat blocks, and TM cards — in a dedicated src/data layer.",
      "Built a persistent Adventure Map navigation that tracks scroll position via an active-section hook and mirrors it in a mobile nav bar.",
      "Implemented an intro sequence with a loading bar and a custom typewriter hook that gates the main UI until it finishes.",
      "Built a Trainer Stats section rendering a hex/radar chart that maps real skill categories onto classic Pokémon stat names (HP, Attack, Sp. Atk, Defense, Sp. Def, Speed).",
      "Added an ambient effects layer — floating background shapes, a pixel particle field, a capture-orb canvas animation, and pokeball-shaped page transitions.",
      "Wired up an easter-egg and achievement system that surfaces toast notifications for hidden interactions, plus an optional background music toggle.",
    ],
    challenges: [
      "Keeping the Pokémon metaphor consistent and game-accurate across every section — type badges, evolution chains, TM cards, hex stats — without it becoming a skin over generic components.",
      "Balancing heavier dependencies (Three.js, GSAP, React Three Fiber) against load performance for a page that still needs to feel fast.",
      "Designing the intro sequence and ambient effects so they add personality without delaying access to the actual content.",
      "Respecting reduced-motion preferences across a UI built almost entirely from animation.",
    ],
    futureScope: [
      "Expand the Pokedex section into a fuller about/lore timeline.",
      "Add more achievements and easter eggs tied to real visitor behavior.",
      "Further optimize the 3D and particle effects for low-end devices.",
    ],
    githubUrl: "https://github.com/kasibaffan/pokefolio",
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug);
}
